// The CHANGELOG area -- see PanelChangelog.h.
//
// Two questions, one screen: WHAT AM I RUNNING, and WHAT CHANGED. The
// version rows answer the first, the content body answers the second.
#include "PanelChangelog.h"

#include "UI/Registry.h"

#include <cstdio>
#include <string>
#include <vector>

// Generated by Overlay/embed_changelog.py at build time: g_Changelog_Data,
// g_Changelog_Size, g_Changelog_Present. See that script for why the
// changelog is embedded rather than read from disk.
#include "Changelog.h"

// Generated by configure_file() from src/RitzVersion.h.in: the fork's base
// commit, its verification flag, and this build's patch date.
#include "RitzVersion.h"

// gamescope's own version string (git describe + compiler).
#include "GamescopeVersion.h"

namespace gamescope
{
	namespace
	{
		// ----------------------------------------------------------------
		//  The changelog text
		// ----------------------------------------------------------------
		// MARKDOWN IS RENDERED AS PLAIN TEXT, DELIBERATELY.
		//
		// The overlay has no Markdown renderer, and adding one to show one
		// document would be the most expensive possible answer. CHANGELOG.md
		// is already written to be read as plain text -- `##` headings,
		// `-` bullets and blank-line paragraphs all survive verbatim, which
		// is the whole reason Markdown looks like that. So each source line
		// becomes exactly one ContentLine, unmodified: no stripping of `#`
		// or `*`, because a half-parsed document ("some markers removed,
		// others not") reads worse than an honest unparsed one, and because
		// stripping markers is a FORMATTING decision, which SPEC §5.2
		// clause 0 puts on the shell's side of the line, not here.
		//
		// Built once. The bytes are static and cannot change while the
		// process runs, so there is no generation to poll the way the Log's
		// ring buffer needs -- rebuilding this per frame would be pure waste.
		const std::vector<ui::ContentLine> &ChangelogLines()
		{
			static const std::vector<ui::ContentLine> s_vecLines = []
			{
				std::vector<ui::ContentLine> vec;

				const char *pszBegin = (const char *)g_Changelog_Data;
				const char *pszEnd   = pszBegin + g_Changelog_Size;

				const char *pszLine = pszBegin;
				for ( const char *p = pszBegin; p <= pszEnd; ++p )
				{
					if ( p == pszEnd || *p == '\n' )
					{
						size_t nLen = (size_t)( p - pszLine );
						// Tolerate CRLF, so a checkout with
						// core.autocrlf does not draw a stray glyph at
						// the end of every single line.
						if ( nLen > 0 && pszLine[ nLen - 1 ] == '\r' )
							nLen--;

						vec.push_back( ui::ContentLine{ 0, std::string(),
							std::string( pszLine, nLen ) } );
						pszLine = p + 1;
					}
				}

				// A trailing newline yields one empty final line; drop it so
				// the body does not always end on blank space.
				if ( !vec.empty() && vec.back().sText.empty() )
					vec.pop_back();

				return vec;
			}();

			return s_vecLines;
		}

		// ----------------------------------------------------------------
		//  Version strings
		// ----------------------------------------------------------------
		// Both are BUILD-TIME facts (src/meson.build derives them; see
		// RitzVersion.h.in for why neither can come from gamescope's own
		// version string). Formatted here, and only here, so the two rows
		// and their Live facts can never disagree about what this build is.

		// The base gamescope: an upstream commit the reader can `git show`.
		std::string BaseVersionLine()
		{
			// The recorded base is verified against git at configure time.
			// When that check fails -- someone rebased the fork onto a
			// different upstream -- saying "fcc1341" anyway would be a
			// LIE, and a version string that silently goes stale is worse
			// than one that admits it. So it says so instead.
			if ( !k_bRitzBaseVerified )
				return std::string( "unknown -- recorded base is not in this history" );

			return std::string( "upstream " ) + k_szRitzBaseCommit;
		}

		// This fork's patch version: a date the reader can compare.
		std::string RitzVersionLine()
		{
			std::string s = k_szRitzPatchDate;
			if ( k_bRitzDirty )
				s += "+";   // built from a dirty tree; the date is approximate
			return s;
		}
	}

	void PanelChangelog_RegisterArea( ui::Registry &reg )
	{
		ui::Area &a = reg.Add( "system.changelog", "Changelog", ui::Section::System );

		a.Keywords( "changelog version history release notes build commit "
		            "gamescope ritz upstream base patch what changed" );
		a.Summary( []
		{
			char sz[ 96 ];
			std::snprintf( sz, sizeof( sz ), "gamescope-ritz %s  ·  %s",
				RitzVersionLine().c_str(), BaseVersionLine().c_str() );
			return std::string( sz );
		} );

		// ---- Version ----------------------------------------------------
		a.Group( "Version" );

		a.Facts( "changelog.gamescope", "gamescope", []{ return BaseVersionLine(); } )
			.Help( "The upstream ValveSoftware/gamescope commit this fork is built on. "
			       "gamescope carries no version tags in this tree, so the commit IS the "
			       "version -- pass it to `git show` to read exactly what it contains." )
			.Keywords( "gamescope upstream base version commit valve" )
			.Live( "base commit", []
			{
				return ui::Fact{ "base commit",
					k_bRitzBaseVerified ? k_szRitzBaseCommit : "unknown" };
			} )
			.Live( "verified", []
			{
				// Says out loud whether the recorded base still holds, so a
				// stale base is visible rather than merely absent.
				return ui::Fact{ "verified", k_bRitzBaseVerified
					? "yes -- ancestor of this build"
					: "NO -- fork was rebased; base is stale" };
			} )
			.Live( "reported", []
			{
				// gamescope's own string, for comparison with what
				// `gamescope --version` prints.
				return ui::Fact{ "reported", k_szGamescopeVersion };
			} );

		a.Facts( "changelog.ritz", "gamescope-ritz", []{ return RitzVersionLine(); } )
			.Help( "This fork's patch version, as the date of the newest commit in the build "
			       "(YYYY-MM-DD). It is the COMMIT date, not the build date, so two builds of "
			       "the same source always report the same version. A trailing + means the "
			       "tree had uncommitted changes when it was configured." )
			.Keywords( "ritz fork version patch date build commit" )
			.Live( "patch date", []
			{
				return ui::Fact{ "patch date", k_szRitzPatchDate };
			} )
			.Live( "commit", []
			{
				return ui::Fact{ "commit", k_szRitzCommit };
			} )
			.Live( "tree", []
			{
				return ui::Fact{ "tree", k_bRitzDirty ? "modified since commit" : "clean" };
			} );

		a.Facts( "changelog.source", "Changelog", []
		{
			char sz[ 64 ];
			if ( !g_Changelog_Present )
				return std::string( "not embedded in this build" );
			std::snprintf( sz, sizeof( sz ), "%zu lines, embedded at build time",
				ChangelogLines().size() );
			return std::string( sz );
		} )
			.Help( "CHANGELOG.md is compiled into the binary rather than read from disk, so it "
			       "always describes the build you are running and can never be a different "
			       "vintage than the binary showing it." )
			.Keywords( "changelog source embedded build file markdown" );

		// ---- the changelog itself ---------------------------------------
		// Same machinery as the Log's body: the area hands over lines, the
		// shell draws and scrolls them.
		a.Content( []{ return ChangelogLines(); } );
		// A changelog is read from the TOP -- newest entries are already
		// first (the date-based policy puts the newest block on top), so
		// following the tail would open every visit on the oldest history.
		a.FollowsTail( []{ return false; } );
	}
}
