// The ABOUT area -- see PanelChangelog.h.
//
// Three questions, one screen: WHAT AM I RUNNING, WHAT CHANGED, and WHAT IS
// IT MADE OF. The version rows answer the first, the changelog answers the
// second, and the licence texts under it answer the third.
#include "PanelChangelog.h"

#include "ChangelogParse.h"
#include "UI/Registry.h"

#include <cstdio>
#include <string>
#include <string_view>
#include <vector>

// Generated by Overlay/embed_changelog.py at build time: g_Changelog_Data,
// g_Changelog_Size, g_Changelog_Present. See that script for why the
// changelog is embedded rather than read from disk.
#include "Changelog.h"

// Generated by Overlay/fonts/embed_font.py (as src/meson.build's
// asset_embed_gen) from the three licence documents this binary has to carry:
// the fork's own LICENSE, the third-party notice, and the fonts' OFL. Same
// byte-array shape as the changelog above, and embedded for a stronger
// reason: the OFL only permits redistributing the Geist glyph data -- which
// IS inside this binary -- if the licence travels with it, and a file
// installed beside the binary can be declined, moved or lost.
#include "LICENSE.h"
#include "THIRD-PARTY-LICENSES.h"
#include "LICENSE-OFL.h"

// Generated by configure_file() from src/RitzVersion.h.in: the fork's base
// commit, its verification flag, and this build's patch date.
#include "RitzVersion.h"

// gamescope's own version string (git describe + compiler).
#include "GamescopeVersion.h"

namespace gamescope
{
	namespace
	{
		// ----------------------------------------------------------------
		//  The changelog text
		// ----------------------------------------------------------------
		// THE MARKDOWN IS PARSED, BUT ONLY THIS DOCUMENT'S MARKDOWN.
		//
		// CHANGELOG.md was previously handed to the shell verbatim, one
		// source line per ContentLine, on the reasoning that a half-parsed
		// document reads worse than an honest unparsed one. That reasoning
		// stands; what changed is that the document now HAS a strict shape
		// (superdoc/claude-instructions/changelog.md), so it can be parsed
		// WHOLLY rather than half. Five line kinds, no Markdown engine --
		// see ChangelogParse.h.
		//
		// WHY PARSE HERE AND NOT IN embed_changelog.py. The parse could run
		// at build time, emitting a table of structs instead of a byte
		// array. It runs at load time instead, for three reasons:
		//
		//   1. IT STAYS TESTABLE. `meson test` runs C++; a Python parser
		//      would need its own harness, and the malformed-input cases
		//      are exactly what has to be tested. As C++ it is one more
		//      file in tests/meson.build.
		//   2. THE EMBED STEP KEEPS ONE JOB. Bytes in, bytes out. A
		//      generated header full of string literals and enum values
		//      has to escape and quote correctly, which is a second thing
		//      that can go wrong in a build rule that currently cannot.
		//   3. IT COSTS NOTHING MEASURABLE. One pass over ~6 kB, once, in
		//      a function-local static -- not per frame.
		//
		// Built once. The bytes are static and cannot change while the
		// process runs, so there is no generation to poll the way the Log's
		// ring buffer needs -- reparsing per frame would be pure waste.
		const std::vector<ui::ContentLine> &ChangelogLines()
		{
			static const std::vector<ui::ContentLine> s_vecLines =
				ParseChangelog( std::string_view(
					(const char *)g_Changelog_Data, g_Changelog_Size ) );

			return s_vecLines;
		}

		// ----------------------------------------------------------------
		//  The licences
		// ----------------------------------------------------------------
		// WHY THEY ARE HERE AND NOT ON A SCREEN OF THEIR OWN. The user's
		// call ("maybe rename the Changelog tab to About and add the
		// licenses to it"): the rail item already answers "what am I
		// running", and "what is it made of" is the same question one step
		// further. A twelfth rail item read by nobody would be a worse home
		// for text that legally has to be reachable.
		//
		// WHAT IS IN HERE, AND WHAT IS NOT. Only what is compiled or
		// embedded INTO the binary, because that is what this binary
		// redistributes: gamescope/gamescope-ritz (BSD-2), the OpenColorIO
		// LUT code and ReShade's FX compiler (BSD-3, both already in the
		// fork's own LICENSE), sol2/Dear ImGui/nlohmann-json/stb/GLM (MIT),
		// SPIRV-Headers (Khronos MIT-style) and the Geist faces (OFL 1.1).
		// System libraries -- wlroots, libdrm, Vulkan, SDL2, LuaJIT and the
		// rest -- are linked dynamically from the distribution and are named
		// but not reproduced; copying their texts in would suggest this
		// binary contains them. See THIRD-PARTY-LICENSES.md.
		//
		// The three documents are separate byte arrays rather than one
		// concatenated file so that each stays the authoritative copy in the
		// tree -- LICENSE is the repo's licence, LICENSE-OFL.txt is the
		// font's own file as shipped by its authors, and neither is
		// duplicated into a third file that could drift from it.
		void AppendDoc( std::vector<ui::ContentLine> &vec,
		                const char *pszHeading,
		                const unsigned char *pData, unsigned uSize )
		{
			if ( pszHeading )
			{
				vec.push_back( ui::ContentLine{} );   // paragraph gap
				ui::ContentLine heading;
				heading.eKind = ui::ContentKind::Heading;
				heading.sText = pszHeading;
				vec.push_back( std::move( heading ) );
				vec.push_back( ui::ContentLine{} );
			}

			// Same parser as the changelog: five line kinds, so a plain
			// licence text comes through as plain text and the notice
			// document's `##`/`###` headings come through as headings.
			// Nothing here needs a Markdown engine.
			for ( ui::ContentLine &line : ParseChangelog(
				std::string_view( (const char *)pData, uSize ) ) )
			{
				vec.push_back( std::move( line ) );
			}
		}

		// The whole body: what changed, then what it is made of. Built once,
		// for the same reason ChangelogLines() is -- the bytes are static.
		const std::vector<ui::ContentLine> &AboutLines()
		{
			static const std::vector<ui::ContentLine> s_vecLines = []
			{
				std::vector<ui::ContentLine> vec = ChangelogLines();

				AppendDoc( vec, nullptr,
					g_Asset_THIRD_PARTY_LICENSES_Data,
					g_Asset_THIRD_PARTY_LICENSES_Size );
				AppendDoc( vec, "gamescope and gamescope-ritz",
					g_Asset_LICENSE_Data, g_Asset_LICENSE_Size );
				AppendDoc( vec, "SIL Open Font License 1.1 (Geist, Geist Mono)",
					g_Asset_LICENSE_OFL_Data, g_Asset_LICENSE_OFL_Size );

				return vec;
			}();

			return s_vecLines;
		}

		// ----------------------------------------------------------------
		//  Version strings
		// ----------------------------------------------------------------
		// Both are BUILD-TIME facts (src/meson.build derives them; see
		// RitzVersion.h.in for why neither can come from gamescope's own
		// version string). Formatted here, and only here, so the two rows
		// and their Live facts can never disagree about what this build is.

		// The base gamescope: an upstream commit the reader can `git show`.
		std::string BaseVersionLine()
		{
			// The recorded base is verified against git at configure time.
			// When that check fails -- someone rebased the fork onto a
			// different upstream -- saying "fcc1341" anyway would be a
			// LIE, and a version string that silently goes stale is worse
			// than one that admits it. So it says so instead.
			if ( !k_bRitzBaseVerified )
				return std::string( "unknown -- recorded base is not in this history" );

			return std::string( "upstream " ) + k_szRitzBaseCommit;
		}

		// This fork's patch version: a date the reader can compare.
		std::string RitzDateLine()
		{
			std::string s = k_szRitzPatchDate;
			if ( k_bRitzDirty )
				s += "+";   // built from a dirty tree; the date is approximate
			return s;
		}

		// This fork's own semantic version, derived at build time from
		// CHANGELOG.md's newest block by Overlay/embed_changelog.py.
		//
		// WHY THE CHANGELOG IS THE VERSION MARKER. The policy in
		// superdoc/claude-instructions/documentation-version-policy.md wants
		// a version marker kept in sync with the newest changelog block, and
		// this project has nowhere to put one: it carries no tags and
		// project() declares no version. Adding a VERSION file or a
		// project(version:) would create a SECOND place to write the number
		// -- and two authoritative-looking numbers that can disagree are
		// worse than one, because the reader cannot tell which lies. Deriving
		// it from the block the policy already governs makes them the same
		// number by construction, so the build enforces what would otherwise
		// be an agent's job to remember.
		std::string RitzVersionLine()
		{
			// "unknown" only when no CHANGELOG.md was embedded at all; the
			// build fails rather than guess when one is present but its
			// newest heading cannot be read.
			return std::string( g_Changelog_Version );
		}
	}

	void PanelChangelog_RegisterArea( ui::Registry &reg )
	{
		// THE ID STAYS system.changelog THOUGH THE LABEL IS NOW "About"
		// (2026-09-09). An id is not a display string: it keys the rail
		// grouping (UI/Registry.cpp), the icon table (UI/Icons.cpp), the
		// palette's stored state and every settings-audit row. Renaming it
		// would move all of that for no user-visible gain, since the user
		// never sees an id. The label and the keywords carry the rename
		// instead, and "changelog" stays in the keywords beside "about" so a
		// search for either word still lands here.
		ui::Area &a = reg.Add( "system.changelog", "About", ui::Section::System );

		a.Keywords( "about changelog version history release notes build commit "
		            "gamescope ritz upstream base patch what changed "
		            "licence license licences licenses legal copyright attribution "
		            "credits open source third party ofl mit bsd geist font imgui "
		            "reshade sol2 stb glm" );
		// All three identity facts, because none substitutes for another: the
		// version says what this fork calls itself, the base commit says what
		// it is a fork OF, and the date says which build of it you are
		// running. Two of the three cannot answer "is my bug already fixed".
		a.Summary( []
		{
			char sz[ 128 ];
			std::snprintf( sz, sizeof( sz ), "%s  ·  %s  ·  %s",
				RitzVersionLine().c_str(), BaseVersionLine().c_str(),
				RitzDateLine().c_str() );
			return std::string( sz );
		} );

		// ---- Version ----------------------------------------------------
		a.Group( "Version" );

		a.Facts( "changelog.gamescope", "gamescope", []{ return BaseVersionLine(); } )
			.Help( "The upstream ValveSoftware/gamescope commit this fork is built on. "
			       "gamescope carries no version tags in this tree, so the commit IS the "
			       "version -- pass it to `git show` to read exactly what it contains." )
			.Keywords( "gamescope upstream base version commit valve" )
			.Live( "base commit", []
			{
				return ui::Fact{ "base commit",
					k_bRitzBaseVerified ? k_szRitzBaseCommit : "unknown" };
			} )
			.Live( "verified", []
			{
				// Says out loud whether the recorded base still holds, so a
				// stale base is visible rather than merely absent.
				return ui::Fact{ "verified", k_bRitzBaseVerified
					? "yes -- ancestor of this build"
					: "NO -- fork was rebased; base is stale" };
			} )
			.Live( "reported", []
			{
				// gamescope's own string, for comparison with what
				// `gamescope --version` prints.
				return ui::Fact{ "reported", k_szGamescopeVersion };
			} );

		a.Facts( "changelog.ritz", "gamescope-ritz", []{ return RitzVersionLine(); } )
			.Help( "This fork's own version. It is DERIVED at build time from the newest "
			       "block in CHANGELOG.md below, not declared anywhere else -- so the number "
			       "shown here and the newest entry you can read cannot disagree. The build "
			       "date underneath tells two builds of the same version apart." )
			.Keywords( "ritz fork version semver patch date build commit changelog" )
			.Live( "version", []
			{
				return ui::Fact{ "version", g_Changelog_Present
					? g_Changelog_Version
					: "unknown -- no changelog embedded" };
			} )
			.Live( "built from", []
			{
				// HEAD's COMMIT date, not the wall clock: two builds of the
				// same source agree, which a build timestamp would not.
				return ui::Fact{ "built from", RitzDateLine() };
			} )
			.Live( "commit", []
			{
				return ui::Fact{ "commit", k_szRitzCommit };
			} )
			.Live( "tree", []
			{
				return ui::Fact{ "tree", k_bRitzDirty ? "modified since commit" : "clean" };
			} );

		a.Facts( "changelog.source", "Changelog", []
		{
			char sz[ 64 ];
			if ( !g_Changelog_Present )
				return std::string( "not embedded in this build" );
			std::snprintf( sz, sizeof( sz ), "%zu lines, embedded at build time",
				ChangelogLines().size() );
			return std::string( sz );
		} )
			.Help( "CHANGELOG.md is compiled into the binary rather than read from disk, so it "
			       "always describes the build you are running and can never be a different "
			       "vintage than the binary showing it." )
			.Keywords( "changelog source embedded build file markdown" );

		// ---- Licences ---------------------------------------------------
		// A row rather than only text at the bottom of a long scroll: the
		// area's own summary and the palette have to be able to say that the
		// licences are IN here, or "reachable in the overlay" would mean
		// "reachable by scrolling past the whole changelog first".
		a.Facts( "changelog.licenses", "Licences", []
		{
			return std::string( "compiled in -- see the end of this page" );
		} )
			.Help( "Everything this binary contains that is not gamescope-ritz's own code: "
			       "gamescope itself, the ReShade effect compiler, Dear ImGui, sol2, stb, GLM, "
			       "nlohmann/json, SPIRV-Headers and the Geist fonts. Their licences are "
			       "compiled into the binary and printed below the changelog. System libraries "
			       "such as wlroots, Vulkan and LuaJIT are loaded from your distribution and "
			       "carry their own licences there." )
			.Keywords( "licence license licences licenses legal copyright attribution credits "
			           "third party open source ofl mit bsd geist font imgui reshade sol2 stb "
			           "glm json spirv" );

		// ---- the changelog, then the licences ----------------------------
		// Same machinery as the Log's body: the area hands over lines, the
		// shell draws and scrolls them.
		a.Content( []{ return AboutLines(); } );
		// A changelog is read from the TOP -- newest entries are already
		// first (the date-based policy puts the newest block on top), so
		// following the tail would open every visit on the oldest history.
		a.FollowsTail( []{ return false; } );
	}
}
